### ISSUE TITLE
MVP 및 플로우차트

### ISSUE THREAD

**Issue by 1000JI** [TEAM3x3/martkurly-ios#10]
플로우차트 & 와이어프레임
- [x] 플로우차트
- [x] 기능 분류
- [x] MVP 확인

**Comment by 1000JI** [comment]
발표 준비?해야함ㅎㅎㅎ

**Comment by KasRoid** [comment]
가끔 새로운 뷰 찾으면 추가하고 있긴한데 아무튼 XD 는 어느정도 완성..

**Comment by jiwooni** [comment]
기약 없는 발표 준비..ㅋㅋㅋㅋ

**Comment by 1000JI** [comment]
User Flow 구성 필요
View + FlowChart
